SetAttrs should take current attributes as argument
geirolz/advxml pull request #199
Opened 2021-04-03 11:12 UTC by pawelkaczor

2021-04-03 11:15 UTC, pawelkaczor commented on modules/core/src/main/scala/advxml/instances/AllTransforInstances.scala
> +    def apply(d: AttributeData, ds: AttributeData*): SetAttrs = SetAttrs(_ => NonEmptyList.of(d, ds: _*))
Another user-friendly apply method is needed that takes a function Map[String, String] => ??? as argument. Don't know though what ??? should be.

2021-04-09 15:23 UTC, geirolz commented
Hi @pawelkaczor thanks for your contribution! Let me check your proposal, could you please add more details and examples(so we can add also some documentation about it) in the meanwhile?

2021-04-09 15:33 UTC, geirolz requested changes
Add documentation

2021-04-09 15:42 UTC, pawelkaczor commented
Hi @geirolz. I would rather treat this issue as a "missing feature". Imagine you just want to update a value of an existing attribute (like value = value + 1). How can I accomplish this with advxml?

2021-04-09 15:45 UTC, pawelkaczor commented
Concrete example:
 
```
  private val dataAgeAttrAddition: ComposableXmlModifier =
    SetAttr(attrs => {
      val age = DataAge(Instant.parse(attrs \@ "CREATED_AT"), clock.instant)
      k"DATA_AGE" := age.asString
    })

```

2021-04-09 15:58 UTC, geirolz commented
> Hi @geirolz. I would rather treat this issue as a "missing feature". Imagine you just want to update a value of an existing attribute (like value = value + 1). How can I accomplish this with advxml?

Good point, I agree. It is achievable but with some workaround.
Does it introduce some breaking changes for the API? Sorry I have no time to see the code now, I will this evening

2021-04-09 18:44 UTC, pawelkaczor commented
A new constructor method has been added to the API. This is not a breaking change.

2021-04-13 13:22 UTC, geirolz commented
@pawelkaczor if you can add some tests for this then we can merge it! 

Please check `XmlTransformationSpec`, `TransformXmlRuleSyntaxTest` and `TransformModifiersTest`

2021-04-13 15:30 UTC, pawelkaczor commented
Done. Not sure if the test fails because of my change?

2021-04-14 07:52 UTC, pawelkaczor commented
Looks like the tests were failing before my changes.

2021-04-14 12:50 UTC, geirolz commented
> Looks like the tests were failing before my changes.

Yes, no problem I'm going to fix it, one done I merge. Thanks again for the contribution!

2021-04-14 12:51 UTC, geirolz approved these changes

2021-04-14 12:54 UTC, merged